plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = property('mod_version')
group = 'com.thedeucecara.digitalexchange'

base {
    archivesName = 'DigitalExchange'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = property('neo_version')

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${property('mod_id')}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenLocal()
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev/"
    }
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation "appeng:appliedenergistics2-neoforge:${property('ae2_version')}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            neo_version      : neo_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_version      : mod_version,
            mod_author       : mod_author
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}
